### ISSUE TITLE
Connecting lines seems broken

### ISSUE THREAD

**Issue by jkbbwr** [retejs/connection-plugin#12] opened 2019-03-23 14:50 UTC
https://i.imgur.com/EAGwxs4.png

When clicking one of the sockets and connecting it to another it starts drawing the line off screen.

**Comment by Ni55aN** [comment] 2019-03-23 15:20
Which version of `rete-connection-plugin`?

**Comment by Armaldio** [comment] 2019-03-28 00:27
Can confirm on `"rete-connection-plugin": "^0.6.0",`

**Comment by Ni55aN** [comment] 2019-03-28 13:23
@Armaldio can you share a whole static html page with an editor?

**Comment by Armaldio** [comment] 2019-03-28 20:47
I don't know if it's what you want but: https://pastebin.com/PeSUh5eL

![image](https://user-images.githubusercontent.com/3089715/55191676-309d0400-5179-11e9-89fa-d4194e0f30d4.png)

**Comment by Ni55aN** [comment] 2019-03-28 21:36
All connected lines have a correct positions, what's wrong?

**Comment by Armaldio** [comment] 2019-03-28 21:42
The problem is, sometimes, links between nodes break (like the top node on the image)
We can then reconnect the node but the old line stay and can't be removed, thought it does nothing.

The screenhot was also made while doing nothing (maybe you tough I was currently dragging the top node socket)

**Comment by Ni55aN** [comment] 2019-03-28 21:57
After all I have to see a live example :)

**Comment by Armaldio** [comment] 2019-03-28 22:00
I'd like to have one but it appears randomly and not very frequently.
Moreover, there is no errors in the console :/

**Comment by Ni55aN** [comment] 2019-03-28 22:04
Does this happen on any example on rete.js.org or codepen?

**Comment by Armaldio** [comment] 2019-03-28 22:24
I don't think so, it never happened there. Only on my code

**Comment by Ni55aN** [comment] 2019-03-31 15:10
In v0.6.4 it should be fixed (I cannot reproduce the issue when browser or OS iterface has a scaling)

**Closed as completed** 2019-04-21 13:56 UTC
